services:
  caddy:
    image: caddy-porkbun:2.8.4
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - PORKBUN_API_KEY=REDACTED
      - PORKBUN_SECRET_API_KEY=REDACTED

volumes:
  caddy_data:
  caddy_config: